/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class BookScannerApp {
    public String getGreeting() {
        return "Book Scanner Java - image-to-PDF pipeline (v0.1-dev)";
    }

    public static void main(String[] args) {
        System.out.println(new BookScannerApp().getGreeting());
    }
}
